### ISSUE TITLE
retreive CI Badge URL's - appveyor in particular

### ISSUE THREAD

**Issue by solvingj** [bincrafters/envy#3]
Appveyor badge url's are dynamic, and must be manually retrieved.  It would be helpful if after creation, envy printed out the badge URL.  At this time, it would be even more helpful if that was exposed as an isolated command or option: `--get-badge-urls` or something. 

If envy was later integrated into a project generator, it could insert the strings directly into the readme. 

Since envy already wraps the appveyor auth and API, i thought it might be the easiest approach.

**Comment by SSE4** [comment]
excellent idea, will look into this

**Comment by solvingj** [comment]
Thanks! reason for needing the printout now is that we just setup brand new CI for all 135 boost libs.  So, I'm going to have to use the web UI to get the appveyor badges :(

**Comment by sigmoidal** [comment]
Isn't the Appveyor badge: https://ci.appveyor.com/project/bincrafters/<projectname-as-on-github> ?

**Comment by solvingj** [comment]
No, Travis works like that, but not Appveyor.  Here's an example: 
`[![Build status](https://ci.appveyor.com/api/projects/status/engdf3vm8ndig4j9?svg=true)](https://ci.appveyor.com/project/BinCrafters/conan-boost-filesystem-jaqy4)`

**Comment by sigmoidal** [comment]
i know they provide a dyn link but if you read: https://www.appveyor.com/docs/status-badges

they explain, how to. i used it before seems to work.

**Comment by sigmoidal** [comment]
i see the issue with same-name repos though. will see when i get back if there is a way.

**Comment by solvingj** [comment]
Well, with envy we can easily script the deletion of the old Appveyor projects, and then enumerate the remaining ones and get back the list of url's which have `conan-boost` in the URL.  With that, we can delete the new projects as well.  And finally, we can script the re-creation of them.

**Comment by SSE4** [comment]
there is no API for status badges in appveyor
as @sigmoidal has specified, you can easily construct badges from project name
for deletion of projects, I am opening another issue
